# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [ ]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [3]:
# Import torch
import torch

# Create random tensor
A = torch.rand(7,7)
A

tensor([[0.0212, 0.7342, 0.9059, 0.2380, 0.1992, 0.8305, 0.1084],
        [0.8322, 0.3543, 0.4101, 0.0246, 0.1100, 0.7552, 0.0849],
        [0.7293, 0.2221, 0.9980, 0.0254, 0.0108, 0.6091, 0.0683],
        [0.5889, 0.3685, 0.0895, 0.0483, 0.3727, 0.7041, 0.1010],
        [0.8381, 0.8868, 0.6142, 0.0942, 0.6329, 0.7377, 0.7164],
        [0.4457, 0.1324, 0.3707, 0.6248, 0.1037, 0.0299, 0.0446],
        [0.5636, 0.3948, 0.5684, 0.5422, 0.0830, 0.8689, 0.0109]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [4]:
# Create another random tensor
B = torch.rand(1,7)

# Perform matrix multiplication

C = torch.mm(A, B.T)
C

tensor([[1.1302],
        [1.1009],
        [0.8786],
        [1.1374],
        [2.3106],
        [0.6599],
        [1.1665]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [7]:
# Set manual seed
torch.manual_seed(0)


# Create two random tensors
A = torch.rand(7,7)
print(A)
B = torch.rand(1,7)
print(B)

# Matrix multiply tensors
C = torch.mm(A, B.T)
C

tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901],
        [0.8964, 0.4556, 0.6323, 0.3489, 0.4017, 0.0223, 0.1689],
        [0.2939, 0.5185, 0.6977, 0.8000, 0.1610, 0.2823, 0.6816],
        [0.9152, 0.3971, 0.8742, 0.4194, 0.5529, 0.9527, 0.0362],
        [0.1852, 0.3734, 0.3051, 0.9320, 0.1759, 0.2698, 0.1507],
        [0.0317, 0.2081, 0.9298, 0.7231, 0.7423, 0.5263, 0.2437],
        [0.5846, 0.0332, 0.1387, 0.2422, 0.8155, 0.7932, 0.2783]])
tensor([[0.4820, 0.8198, 0.9971, 0.6984, 0.5675, 0.8352, 0.2056]])


tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [10]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)
A = torch.rand(1,7)
A


tensor([[0.5932, 0.1123, 0.1535, 0.2417, 0.7262, 0.7011, 0.2038]])


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [12]:
# Set random seed
torch.cuda.manual_seed(1234)

# Check for access to GPU
device = 'cuda' if torch.cuda.is_available() else 'cpu'

# Create two random tensors on GPU
A = torch.rand(2,3)
B = torch.rand(2,3)
A.to(device)
B.to(device)

tensor([[0.9442, 0.8802, 0.0012],
        [0.5936, 0.4158, 0.4177]], device='cuda:0')


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [13]:
# Perform matmul on tensor_A and tensor_B
C = torch.mm(A, B.T)
C


tensor([[1.4165, 0.8352],
        [0.6804, 0.4161]])

### 8. Find the maximum and minimum values of the output of 7.

In [15]:
# Find max
print(C.max())

# Find min
print(C.min())


tensor(1.4165)
tensor(0.4161)


### 9. Find the maximum and minimum index values of the output of 7.

In [16]:
# Find arg max
print(C.argmax())

# Find arg min
print(C.argmin())


tensor(0)
tensor(3)



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [19]:
# Set seed
torch.manual_seed(7)

# Create random tensor
A = torch.rand(1,1,1,10)
print(A)
print(A.shape)

# Remove single dimensions
# torch.squeeze(A)
# print(A).          This dont work because in pytorch the tensors are copied and not changed for changing operations the method usally contains _
# print(A.shape)

# Print out tensors and their shapes
B = torch.squeeze(A)
print(B)
print(B.shape)


tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]])
torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513])
torch.Size([10])
